/* eslint-disable no-unused-vars */

export enum Type {
  CPU = 'CPU',
  Monitor = 'Monitor',
  Estabilizador = 'Estabilizador',
  Nobreak = 'Nobreak',
  Escaneador = 'Escaneador',
  Webcam = 'Webcam',
  Hub = 'Hub',
  Switch = 'Switch',
  Notebook = 'Notebook',
  Datashow = 'Datashow',
  Scanner = 'Scanner',
  Impressora = 'Impressora',
  Roteador = 'Roteador',
  Tablet = 'Tablet',
  Tv = 'Tv',
  Fax = 'Fax',
  Telefone = 'Telefone',
  Smartphone = 'Smartphone',
  Projetor = 'Projetor',
  Tela_de_Projecao = 'Tela de Projeção',
  Camera = 'Camera',
  Caixa_de_som = 'Caixa de som',
  Impressora_termica = 'Impressora térmica',
  Leitor_de_codigo_de_barras = 'Leitor de codigo de barras',
  Mesa_Digitalizadora = 'Mesa Digitalizadora',
  Leitor_biometrico = 'Leitor biométrico',
  Receptor = 'Receptor',
  Extrator_de_dados = 'Extrator de dados',
  Transformador = 'Transformador',
  Coletor_de_Assinatura = 'Coletor de Assinatura',
  Kit_cenario = 'Kit cenário',
  Dispositivo_de_biometria_facial = 'Dispositivo de biometria facial',
  Servidor_de_rede = 'Servidor de rede',
  Hd_Externo = 'Hd Externo',
  Protetor_eletronico = 'Protetor eletrônico'
}

export const generalTypes = [
  Type.Webcam,
  Type.Escaneador,
  Type.Hub,
  Type.Switch,
  Type.Notebook,
  Type.Datashow,
  Type.Scanner,
  Type.Impressora,
  Type.Roteador,
  Type.Tablet,
  Type.Tv,
  Type.Fax,
  Type.Telefone,
  Type.Smartphone,
  Type.Projetor,
  Type.Tela_de_Projecao,
  Type.Camera,
  Type.Caixa_de_som,
  Type.Impressora_termica,
  Type.Leitor_de_codigo_de_barras,
  Type.Mesa_Digitalizadora,
  Type.Leitor_biometrico,
  Type.Receptor,
  Type.Extrator_de_dados,
  Type.Transformador,
  Type.Coletor_de_Assinatura,
  Type.Kit_cenario,
  Type.Dispositivo_de_biometria_facial,
  Type.Servidor_de_rede,
  Type.Hd_Externo,
  Type.Protetor_eletronico
]
