name: Release

on: 
  push:
    branches:
      - teste-release-develop4
    
jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Cria arquivo .env
      run: |
          touch ./scripts/.env
          echo TOKEN=${{ secrets.API_TOKEN_GITHUB }} >> ./scripts/.env
          echo RELEASE_MAJOR=true >> ./scripts/.env
          mkdir analytics-raw-data

    - name: Gera release
      run: cd scripts && yarn install && node release.js

    - name: Envia métricas para repositório de DOC
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"
          git clone --single-branch --branch main "https://x-access-token:${{secrets.API_TOKEN_GITHUB}}@github.com/fga-eps-mds/${{secrets.GIT_DOC_REPO}}" ${{secrets.GIT_DOC_REPO}}
          mkdir -p ${{secrets.GIT_DOC_REPO}}/analytics-raw-data
          cp -R analytics-raw-data/*.json ${{secrets.GIT_DOC_REPO}}/analytics-raw-data
          cd ${{secrets.GIT_DOC_REPO}}
          git add .
          git commit -m "Adicionando métricas do repositório ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push