name: Release

on: 
  pull_request:
    branches:
      - teste-release-main
    types: [ closed ]
    
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Cria arquivo .env
      run: |
          touch ./scripts/.env
          echo TOKEN=${{ secrets.API_TOKEN_GITHUB }} >> ./scripts/.env
          echo RELEASE_MAJOR=${{ contains(github.event.pull_request.labels.*.name, 'MAJOR RELEASE') }} >> ./scripts/.env
          echo RELEASE_MINOR=${{ contains(github.event.pull_request.labels.*.name, 'MINOR RELEASE') }} >> ./scripts/.env
          echo RELEASE_FIX=${{ contains(github.event.pull_request.labels.*.name, 'FIX RELEASE') }} >> ./scripts/.env
          echo NOT_RELEASE=${{ contains(github.event.pull_request.labels.*.name, 'NOT RELEASE') }} >> ./scripts/.env

    - name: Gera release
      run: cd scripts && yarn install && node release.js