name: Release

on: 
  push:
    branches:
      - teste-release-develop4
    
jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Cria arquivo .env
      run: |
          touch ./scripts/.env
          echo TOKEN=${{ secrets.API_TOKEN_GITHUB }} >> ./scripts/.env
          echo RELEASE_MAJOR=true >> ./scripts/.env

    - name: Gera release
      run: cd scripts && yarn install && node release.js